### ISSUE TITLE
Show different IIIF manifest structures

### ISSUE THREAD

**Issue by j-panzer** [tify-iiif-viewer/tify#111]
For the NLH AHN project (Historical Newspapers) we need to show different structures. The IIIF Presentation API doesn't support this, but we could create specific manifests, which reflects a specific view, so that we can support navigation over different structure types.

1) Page based: As usual via pages and logical Structural elements.
2) Articles based: Via articles, whereby not whole pages, but the scans of the page excerpts of the articles are to be displayed. An article then consists of one scan or a sequence of scans, which can then be used to navigate (previous/next section, start of article (previous/next excerpt, beginning of article, previous/next article).

The first question is which component could help to solve this problem? Choose a structure from the hit-list and open it in TIFY with the specific manifest or switch from TIFY. In the latter case, how should TIFY know about the different structures?

Any ideas are welcome :)

**Comment by t11r** [comment]
As you already mentioned, the IIIF API does not support this, so it is probably outside of TIFY's scope of responsibility. It is not possible to modify the manifest after it has been loaded.

However, I am not sure that I understand correctly what you are trying to achieve. Could you add a bit more information about your specific use case, maybe add a link?

**Comment by j-panzer** [comment]
We have the page view, where whole pages are displayed (common case). For an additional article-based view, the page parts of an article (excerpts belonging to an article) were scanned. So we have different sets of images. Both views have the usual navigation (previous/next page, beginning section, next/previous section, start page), which is described in the manifest.

**Question:** I would like to ask whether it is possible to pass multiple manifests to TIFY so that it is possible to switch between the views (e.g. via toggle)?

**Feature:** This might also be interesting, for example, to display different records at the same time side by side, e.g. as an additional feature of TIFY.

**Comment by t11r** [comment]
Multiple manifest would be a use case for a IIIF collection, which will be supported with one of the next releases. With the upcoming release (hopefully within a few days), replacing the manifest is already possible though.

The upcoming release also supports multiple instances, so different manifests can be shown side by side.

**Comment by t11r** [comment]
Please check out the latest release and let us know if this addresses this issue.

**Comment by t11r** [comment]
Has this been resolved?

**Comment by ipf** [comment]
@paulpestov will talk to @j-panzer

**Comment by j-panzer** [comment]
Hi, sorry for the late reply. Yes, multiple instances and thus the possibility to display multiple manifests meets our (NLH AHN project) requirements. Thanks!
