### ISSUE TITLE
Support startCanvas parameter for sequences.

### ISSUE THREAD

**Issue by jeremydeclerck** [tify-iiif-viewer/tify#112]
Tify should set the first canvas in a sequence based on the startCanvas parameter. It's possible to set the URL parameter like this: 
`tify={"pages":[2]}`

But this should not be necessary because we would have read the manifest to get the startCanvas value. So this should be handled by the viewer.

**Comment by t11r** [comment]
Good point, this is going to be implemented. Could you provide the URL of a manifest with `startCanvas` set?

**Comment by jeremydeclerck** [comment]
Yes, here is an example of a manifest with a startCanvas:
https://iiif.kmska.be/iiif/2/1048/manifest.json

**Comment by michielkenis** [comment]
As I'm interested in this as well, I was wondering if there are any updates on this?

**Comment by t11r** [comment]
This is still near the top of our roadmap, but due to illness and holidays, we are a bit short on staff and thus behind schedule. I cannot give you a definitive date, but it will come soon.
