### ISSUE TITLE
Seitenladefehler

### ISSUE THREAD

**Issue by otti73** [tify-iiif-viewer/tify#113]
Beim Öffnen der Seite

https://gdz.sub.uni-goettingen.de/id/PPN547285191

bekomme ich die Fehlermeldung

Error loading info file for page 1: Internal Server Error

**Comment by t11r** [comment]
Das liegt nicht an TIFY, sondern am Server des GDZ. Meiner Information nach wird an dem Problem bereits gearbeitet.
