### ISSUE TITLE
Add documentation for fulltext usage

### ISSUE THREAD

**Issue by datazuul** [tify-iiif-viewer/tify#121]
It is stated here https://www.sub.uni-goettingen.de/en/digital-library/digital-tools/dokumentbetrachter-tify/ and here https://github.com/tify-iiif-viewer/tify/blob/main/src/components/ViewFulltext.vue that fulltext is supported.

I can not find an example / demo of this functionality. Source code uses canvas otherContent annotation list to get fulltext.
When I use a manifest with fulltext (hOCR), e.g. https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb11475472/manifest 
I can not see any GUI element for fulltext toggling or showing?

Please add documentation  and demo for fulltext view.

**Comment by datazuul** [comment]
I found a demo on the homepage "[The Natural Method of Healing](javascript:;)/[Wellcome Collection](https://wellcomecollection.org/works/hcz4pz7m)". A "Fulltext" button is shown.

Please add documentation for this and how fulltext has to be embedded into manifests that it can be shown.

**Comment by t11r** [comment]
We may add more documentation regarding the IIIF manifest in the future. For now, please see the [documentation for the IIIF Presentation API](https://iiif.io/api/presentation/2.0/#canvas), the property used for fulltext is _otherContent_ on any _canvas_. This is evaluated by TIFY at https://github.com/tify-iiif-viewer/tify/blob/main/src/components/ViewFulltext.vue#L34.

**Comment by ipf** [comment]
An example is [here](https://gdz.sub.uni-goettingen.de/id/PPN235181684_0033?origin=%2Fcollection%2Fmathematica&collection=mathematica&tify=%7B%22view%22%3A%22fulltext%22%7D) and [this](https://manifests.sub.uni-goettingen.de/iiif/presentation/PPN235181684_0033/manifest?version=2d651b49) is the manifest where we used it
