### ISSUE TITLE
use bigger image for https://tify.rocks/

### ISSUE THREAD

**Issue by andrisi** [tify-iiif-viewer/tify#128]
To showcase Tify, you could host a bigger image file somewhere through IIIF. I'd suggest the 30k x 17k pixel image of  [The Garden of Earthly Delights](https://commons.wikimedia.org/wiki/File:The_Garden_of_Earthly_Delights,_ca._1480-1505.jpg
)  from Wikimedia. Your viewer seems to handle the transition better than the [IIPMooViewer](https://iipimage.sourceforge.io/documentation/iipmooviewer/) I use now so it is worth to do a better demo of yours.

**Comment by t11r** [comment]
Thank you for the suggestion, I like it. Do have the URL of a IIIF manifest with said image or another large one at hand?

**Comment by andrisi** [comment]
No, or not publicly, so you'd need to host it, and also see #129

**Comment by t11r** [comment]
Closing this because it is not directly related to TIFY, and we won't run our own IIIF server anytime soon. If you happen to find a nice, large image available as IIIF, please open an issue on [the website repo](https://github.com/tify-iiif-viewer/tify-website/).
