### ISSUE TITLE
key bindings

### ISSUE THREAD

**Issue by eroux** [tify-iiif-viewer/tify#138]
Some of our users require some keyboard navigation when they use our viewer. Here are our current key bindings:
- `n`: next image
- `p`: previous image
- `page down`: next image
- `page up`: previous image
- `home` (the button that usually goes at the beginning of a line): go back to the left of the image, not changing the vertical position
- `end` (the button that usually goes at the end of a line): go to the right of the image, not changing the vertical position
- `+`: zoom in
- `-`: zoom out
- `arrow (left, up, right, down)`: move in the image (that seems implemented already)
- `space` move right in horizontal images, move down in vertical images (depending on their ratio)

**Comment by t11r** [comment]
Please [check out the user guide](https://github.com/tify-iiif-viewer/tify/blob/main/doc/user-guide.en.md#key-bindings), there are already keybindings available for all actions. They can not be configured yet though.

**Comment by eroux** [comment]
wonderful, thanks! it would be really useful to have them configurable
