### ISSUE TITLE
Problem with the TOC

### ISSUE THREAD

**Issue by morpheus-87** [tify-iiif-viewer/tify#16]
The following manifest does not render the TOC properly:
https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00026283/manifest
In my opinion, TIFY does not know how to handle multi-language labels.

**Comment by ipf** [comment]
Hello @morpheus-87 and thanks for your issue.
Could you please try, if the referenced pull request solves your issue?

**Comment by morpheus-87** [comment]
Hello @ipf, the referenced pr solves my issue, yes. Thank you for your help!
