### ISSUE TITLE
iiif.link

### ISSUE THREAD

**Issue by atomotic** [tify-iiif-viewer/tify#165]
A few years ago, I created https://iiif.link, a tool that allows users to browse an IIIF manifest and generate a short link pointing to a specific position on a specific canvas.

Initially, the tool was built using OpenSeadragon with raw IIIF support (just vanilla fetch() and JSON parsing). While it served its purpose, it remained somewhat incomplete as I didn't want to reinvent the wheel by creating another viewer from scratch.

However, I've been keeping an eye on TIFY for a long time, and its feature of reflecting the state in a bookmarkable URL made it perfect for my needs.

As such, I rewrote https://iiif.link to utilize TIFY (specifically, the iiif3 branch).  
For the UI, I adapted your index.html file.  
Once users have a view with the "Create link" option, they can generate a short permalink.

Examples:

* https://iiif.link/id/240bjrbmta5d
* https://iiif.link/id/5dqked5ixz8k

Additionally, I've made available a redirect to vanilla TIFY URLs:

* https://iiif.link/r/240bjrbmta5d
* https://iiif.link/r/5dqked5ixz8k

The app is a minimal Go application, persisting to a SQLite database. I need to clean the code a bit, then will release.

Thanks, TIFY is lovely ❤️

**Comment by t11r** [comment]
Thank you for your kind words and for letting us know about your project! However, I would not advise to base a production website on an unreviewed branch :wink:

Luckily, TIFY now officially supports IIIF 3 :partying_face:

**Comment by atomotic** [comment]
Great, I just updated it. The code is here https://github.com/atomotic/iiif.link
This service is quite unknown and is not used by anyone but me.

**Comment by t11r** [comment]
Closing this for now, please open a new issue if required.
