### ISSUE TITLE
TIFY fails to load if translation is missing

### ISSUE THREAD

**Issue by hrvoj3e** [tify-iiif-viewer/tify#170]
Using version `0.29.2`

```
tify.js:14 Uncaught (in promise) Error: SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at tify.js:14:13438
(anonymous)	@	tify.js:14
Promise.then (async)		
```

![image](https://github.com/tify-iiif-viewer/tify/assets/4988133/e5dcee8b-3ee4-4980-b344-cd88cfcce93f)

I see from README that `fallbackLanguage` is by default `en` but anyway the viewer will not load

> fallbackLanguage: string, default 'en'
>
> The language to be used for strings from the IIIF manifest that are not available in the current language. If no value matches language or fallbackLanguage, the first available language is displayed.

---
Using version `0.30.2`

![image](https://github.com/tify-iiif-viewer/tify/assets/4988133/f770874a-1884-4da3-9b10-8f5381828de5)

**Comment by t11r** [comment]
`fallbackLanguage` only concerns strings from the IIIF manifest, not the interface language.

The current behavior is intended, but I recognize that we could soften the impact by allowing TIFY to load if the translation is missing or invalid and just display an error message. Or maybe you have another suggestion?

**Comment by hrvoj3e** [comment]
My bad about `fallbackLanguage` - I just assumed it is for UI.

I suggest that you define a fallback for UI language. 
 - That should cover cases where someone wants another fallback UI language other than EN.
 
Viewer should load in any case (never break) and EN is always available so user can see images (that is the point of this viewer).

**Comment by t11r** [comment]
Thanks! To keep things simple, I would stick to the previous language if loading a translation fails. This will be part of the next minor release.
