### ISSUE TITLE
Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by Ingolf63** [tify-iiif-viewer/tify#189]
![Bildschirmfoto_12-8-2024_15446_gdz sub uni-goettingen de](https://github.com/user-attachments/assets/1b97344a-bb0b-4911-a1ea-ad1065daa40b)

**Comment by Ingolf63** [comment]
Help me, please.
KINDLY REGARDS

**Comment by t11r** [comment]
This looks like an issue with the repository, not with TIFY. Could you add a link, please?

**Comment by Ingolf63** [comment]
Thanks for your quick answer. At first I go to "https://data.cerl.org/siebmacher/_index/lemma". There I enter the search term: "https://data.cerl.org/siebmacher/_search?query=Dobra&from=0". Then I click on one of the results and I get the result already shown by screenshot at the following link: "https://gdz.sub.uni-goettingen.de/id/PPN828635498?tify=%7B%22pages%22:%5B83%5D%7D".

**Comment by t11r** [comment]
As I suspected, the GDZ website is broken, not TIFY. [Please let them know.](https://gdz.sub.uni-goettingen.de/feedback/)

**Comment by t11r** [comment]
The issue at GDZ has been fixed.
