### ISSUE TITLE
TypeError for some JP2 files

### ISSUE THREAD

**Issue by mcreece** [tify-iiif-viewer/tify#26]
Some of the manifests I'm loading are throwing a TypeError. In Firefox the error is "t is null" and in Chrome the error is "Cannot read property '@value' of null. The manifest is here: https://digital.lib.ecu.edu/encore/manifests/00000002/00002555.json

**Comment by doganzm** [comment]
Did you try validating your manifest? sc:Manifest['license'] must have a URI or resource!

**Comment by mcreece** [comment]
That was it...thanks!
