### ISSUE TITLE
Include Openseadragon as NPM dependency instead of git checkout

### ISSUE THREAD

**Issue by bencomp** [tify-iiif-viewer/tify#27]
When I install tify using `npm`, a post-install step is performed that installs Openseadragon as a git checkout.

Openseadragon is available as an NPM package: https://www.npmjs.com/package/openseadragon – isn't it better to make it a normal dependency?

**Comment by bencomp** [comment]
I created a branch, which seems to work: https://github.com/bencomp/tify/tree/27-osd-dependency

**Comment by ipf** [comment]
Hey @bencomp,
thanks a lot for your contribution!

Indeed, Openseadragon is available as NPM package, but using this instead of our custom build results in a tify version twice as big, so we decided to only use the components we need and use the custom install.
