### ISSUE TITLE
Should full-text view only show annotations with 'sc:painting' motivation?

### ISSUE THREAD

**Issue by bencomp** [tify-iiif-viewer/tify#28]
I *think* the full-text panel should only load text annotations that have the motivation `sc:painting`, as they represent text that is 'painted' on the canvas. But I would like to know what others think :)

**Comment by t11r** [comment]
Hi @bencomp, on behalf of the previous maintainers at @subugoe, let me express my apologies for the delayed answer. I took over a few days ago, and things will improve now.

I agree with your assumption. Could you please provide a manifest which includes annotations other than `sc:painting` showing in the fulltext panel, or a link to a practical example?
