### ISSUE TITLE
Annotations with array of bodies don't load

### ISSUE THREAD

**Issue by bencomp** [tify-iiif-viewer/tify#29]
When the JSON-LD serialisation of an (Open) annotation in an AnnotationList has an array of objects in the `resource` key, Tify ignores all of them.

This is a snippet of an annotation with an array of annotation bodies, which only has one entry:
```
"resource" : [ {
        "@type" : "dctypes:Text",
        "http://dev.llgc.org.uk/sas/full_text" : "<img src=\"../abnormalhieratic/wp-content/uploads/2018/10/2Dd.svg\" alt=\"\" width=\"55\" height=\"34\" />\nType: VerbTransliteration: DdTranslation: Has said",
        "format" : "text/html",
        "chars" : "<p><img src=\"../abnormalhieratic/wp-content/uploads/2018/10/2Dd.svg\" alt=\"\" width=\"55\" height=\"34\" /></p>\n<p>Type: Verb<br /><br />Transliteration: Dd<br /><br />Translation: Has said<br /><br /></p>"
        } ],
```

The FullText pane only looks for either a `chars` entry in the `resource` *or* an `@id`, the text is not loaded – without any error message. It would be great if the annotation were loaded.

**Comment by t11r** [comment]
Could you please provide a full manifest file with which this issue occurs?

**Comment by t11r** [comment]
Closed due to inactivity.
