### ISSUE TITLE
Switching from image or info panel to toc may result in long parsing times

### ISSUE THREAD

**Issue by ipf** [tify-iiif-viewer/tify#3]
Example: https://iiif.ub.uni-leipzig.de/0000000011/manifest.json

**Comment by t11r** [comment]
With a file size of 8.6 MB, that manifest is unusually large, so it’s no wonder parsing takes some time. However, with the current release 0.8.0, all panels are cached, so there should be only a few seconds of waiting time when the TOC panel is first opened. Please check if there are any other issues; if so, a more detailed description would be greatly appreciated.
