### ISSUE TITLE
Load image that are not provided via IIIF image API

### ISSUE THREAD

**Issue by ipf** [tify-iiif-viewer/tify#31]
Images may be served as static images instead of Tiles delivered by the IIIF Image API.
These images are not shown in the Image section of the viewer. 

An Example manifest:
https://iiif.manducus.net/manifests/exp/static.json

In TIFY:
https://tify.sub.uni-goettingen.de/demo.html?manifest=https://iiif.manducus.net/manifests/exp/static.json

**Comment by doganzm** [comment]
Mirador supports this!

Usually there are several sizes available for a given image as in Wikimedia or in various METS files from the libraries. If a repository can return the appropriate sized image in response to a request that conforms to the IIIF Image API then all these images can be viewed in TIFY without the need for an image server.
