### ISSUE TITLE
Problem to display Ranges w/o canvases

### ISSUE THREAD

**Issue by regisrob** [tify-iiif-viewer/tify#32]
Tify fails to display Ranges without a `canvases` property, for instance this the case for all the Manifests from Cambridge University (example: https://tify.sub.uni-goettingen.de/demo.html?manifest=https://cudl.lib.cam.ac.uk/iiif/MS-ADD-08640).

Tify throws the error "TypeError: "t.$root.canvases[(o.firstPage - 1)] is undefined"", which breaks both the "Info" and "Contents" panels.

According to Presentation API 2.1, the `canvases` property is optional on a Range.

Tify should probably ignore the Range without `canvases` (which is always the first one in the case of Cambridge Manifests). This is what Mirador does. 
Or instead try to display that Range anyway, as UV does (even if the rendering is not completely satisfactory in the Index panel): http://universalviewer.io/uv.html?manifest=https://cudl.lib.cam.ac.uk/iiif/MS-ADD-08640

**Comment by t11r** [comment]
Hi @regisrob, thank you for your report. On behalf of the previous maintainers at @subugoe, let me express my apologies for the delayed answer. I took over a few days ago, and things will improve now.

This is indeed a bug. I will try to provide a fix with one of the next TIFY versions.

**Comment by regisrob** [comment]
👍 Thanks
