### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by t11r** [tify-iiif-viewer/tify#34]
A quick search revealed several services based on TIFY that removed the help tab and do not provide a link to the source as required by the AGPL 3.0, one of which ([Glagoljica.hr](https://glagoljica.hr/)) is even linked on @subugoe's website. Does this mean TIFY can be used under another license which does not require a link to the source?

**Comment by ipf** [comment]
Thanks for the hint, we'll definetly check that!

**Comment by t11r** [comment]
Any update on this? If you don't mind my saying, what's the point in using a rather restrictive open source license when violations are ignored?

**Comment by ipf** [comment]
The institution has been notified by mail.

**Comment by t11r** [comment]
... and they added a link to our source (but not to theirs). However, they only added the Croatian translation, which we could (and should) add to the official repository in turn.
