### ISSUE TITLE
Help installing as Vue component

### ISSUE THREAD

**Issue by micheljp** [tify-iiif-viewer/tify#35]
Any ideas on how I would go about utilizing this as a Vue component?

**Comment by t11r** [comment]
I am afraid that is currently not possible. While TIFY was created with Vue, it was conceived as a stand-alone application, not a Vue component. You would have to either modify several files or – probably easier – write a wrapper component.

Hopefully @subugoe is going to resume developing TIFY in the near future, and maybe one of the next versions will natively allow this.

**Comment by micheljp** [comment]
What I've done to get this working in my vue app is this:

I installed tify via npm and copied tify.js and tify.css to the public assets directory.

I then created a Viewer.vue component with the container div `<div id="viewer"></div>` and on created() i attach the js script tag and tify config via this hack. 
```
created() {
      let tifyConfig = document.createElement('script');
      let code = 'tifyOptions = { options }'
      tifyConfig.appendChild(document.createTextNode(code))
      document.body.appendChild(tifyConfig)

      let tify = document.createElement('script')
      tify.setAttribute('src',"/tify.js")
      document.head.appendChild(tify)
    }
```
