### ISSUE TITLE
Add view option?

### ISSUE THREAD

**Issue by hmmlsystems** [tify-iiif-viewer/tify#36]
Great project! Keep up the great work!

Would love to see an option (https://github.com/subugoe/tify#options) added where you can set the view on load. The user can still change it but it would be nice to set it on load vs. right now it loads by default with the Info view.

Maybe:

**view** (string, default:”info”): Controls what view is displayed. By default, TIFY displays the Info view. Possible values: pages ({"view":"thumbnails"}), info ({"view":"info"}), export ({"view":"export"}), help ({"view":"help"}), or “” ({"view":""}).

Thanks.

Currently I’m using this JavaScript as a work around:
```
function updateURL() {
			if (history.pushState) {
				  var newurl = window.location.protocol + "//" + window.location.host + window.location.pathname + '?tify={"view":"thumbnails"}';
				  window.history.pushState({path:newurl},'',newurl);
			  }
		}
```

**Comment by t11r** [comment]
Hi @hmmlsystems, on behalf of the previous maintainers at @subugoe, let me express my apologies for the delayed answer. I took over a few days ago, and things will improve now.

Nice idea, it will be implemented it in one of the upcoming releases.

**Comment by t11r** [comment]
The latest release has an option `view` to set the initial view.
