### ISSUE TITLE
Wrong value displayed for saturation filter when set to zero

### ISSUE THREAD

**Issue by t11r** [tify-iiif-viewer/tify#37]
When the saturation filter is set to 0, the label in the filter popup should display "Saturation: 0 %", but instead it displays "Saturation: 100 %", and the range slider "jumps" when hitting zero.

**Comment by t11r** [comment]
Will be fixed in the next release.

**Comment by frank-sub** [comment]
@t11r :
First of all my apoligies. I am totally new to the team (subugoe) and git isn't working as it is supposed to be; so I am not able at this moment to create a proper pull request. (Hopefully I will be tomorrow).
That worked for me: Scan.vue@118 && @127
if the value of params.filters.saturate is 0, the first part of the logical expression evaluates to 0 and therefore to false (0 * 100 === 0), so the the whole expression always evaluates to 100.
So I used this for the label by treating the value of 0 separately:
{{ $root.params.filters.saturate * 100 === 0 ? 0 : Math.round($root.params.filters.saturate * 100 || 100) }}&nbsp;%
and this for the corresponding value:
:value="$root.params.filters.saturate === 0 ? 0 : ($root.params.filters.saturate || 1)"

**Comment by t11r** [comment]
Hi @frank-sub, welcome to the team! I am sure you will figure git out 😉

If you allow me a tiny hint: [Using backticks (or triple backticks) around code in Markdown makes it much more readable](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code).

With my previous comment I meant that I already fixed it (using a solution similar to yours, but with [computed values](https://vuejs.org/v2/guide/computed.html)), and it will be part of the next release. Thank you for your suggestion though!
