### ISSUE TITLE
Make TIFY happy again

### ISSUE THREAD

**Issue by t11r** [tify-iiif-viewer/tify#40]
In 2017, I created TIFY at the Göttingen State and University Library (@subugoe). TIFY got some attention from the IIIF community and is built upon by several projects. Among the upcoming Mirador&nbsp;3, Universal Viewer and a few others, TIFY fills its own niche by offering some unique features, and can be a valuable tool for making image collections and related metadata publicly available.

However, since I left my job to found my own company, development has stalled. There has not been a release for over a year (which only @subugoe staff could do), most issues did not even get a reply, and TIFY remains almost invisible among over 200 repositories, most of which are stagnant or only used internally.

This makes TIFY, me, and possibly its users sad.

To increase visibility and to bundle related repositories, like an upcoming website and plugins, TIFY should be moved to its own GitHub organization, which I am hereby offering to maintain. Unlike another fork, this would keep all issues (and stars :relieved:) and redirect visitors to the new official repository. Issues would be taken care of, and I already have plans for further development. Of course, TIFY will always remain open source.

@subugoe and @doganzm (head of Software & Service Development), what do you say, :+1: or :-1:?

The opinions of users, contributors (@ipf, @smuehlh, @pierrz, @JamesWChan, and @asajedi), and organizations who use TIFY (@nationalarchives and @ecds, among others) are also welcome.

**Comment by pierrz** [comment]
Thank you @t11r for all your work, and for this proposal that seems to make plenty of sense.
I'd be happy to help if needs be and I will also commit very soon a dark-themed, minimal version for Tify. Hope it might come along well with what is already planned.

**Comment by ipf** [comment]
Done!

**Comment by t11r** [comment]
Thank you! TIFY now resides at https://github.com/tify-iiif-viewer/tify.
