### ISSUE TITLE
Add support for collections

### ISSUE THREAD

**Issue by eroux** [tify-iiif-viewer/tify#44]
I was quite excited to discover tify as it seems much more mobile friendly than the other viewers I've seen so far! I would love to try it but the big blocker is support for iiif collections, is this a planned feature?

I'm trying to get https://iiifpres.bdrc.io/2.1.1/collection/wio:bdr:W22084 to work on the [demo](http://tify.sub.uni-goettingen.de/demo.html?manifest=https://iiifpres.bdrc.io/2.1.1/collection/wio:bdr:W22084) but it triggers a JS error:

```
TypeError: "this.manifest.sequences is undefined"
```

Ideally the display would be similar to mirador2:

http://library.bdrc.io/view/bdr:W22084

(lazy loading subcollections and manifests if they appear on screen)

**Comment by t11r** [comment]
Thank you for your report. TIFY does not support collections yet, but should definitely not just display a blank screen when a valid manifest like yours is loaded.

We are currently discussing the future roadmap for TIFY, and support for collections seems like an important feature that can be implemented with relatively little effort. We will keep you updated.

**Comment by eroux** [comment]
Excellent, that's very exciting! Tify is currently the only off the shelf option for mobile, supporting collections in a nice way would be a game changer in the iiif world I think

**Comment by t11r** [comment]
Implemented in #134, release will come within a few days.

**Comment by ipf** [comment]
Collection support is now included - see [this](https://tify.rocks/?manifest=https%3A%2F%2Fiiif.wellcomecollection.org%2Fpresentation%2Fv2%2Fb19974760&tify=%7B%22view%22%3A%22collection%22%7D) as example

**Comment by eroux** [comment]
wonderful, thanks a lot!
