### ISSUE TITLE
Installation on windows fails

### ISSUE THREAD

**Issue by ipf** [tify-iiif-viewer/tify#52]
See https://ci.appveyor.com/project/ipf/tify/builds/28254853
Maybe caused by some escapings

**Comment by mlichtenberg** [comment]
On Windows 10, I got past the error by changing line 20 of package.json from this:

    "fix-openseadragon": "replace '\\}\\(this, function \\(\\) \\{' '}(window, function () {' ./openseadragon/src/openseadragon.js",

To this:

    "fix-openseadragon": "replace \"\\}\\(this, function \\(\\) \\{\" \"}(window, function () {\" ./openseadragon/src/openseadragon.js",

I don't have easy access to Linux/MacOS, so I have no way of testing to make sure this fix doesn't break anything on those platforms.

**Comment by t11r** [comment]
Many thanks for the suggestion, @mlichtenberg! This seems to be working fine on Linux and Windows (CLI and git bash).
