### ISSUE TITLE
Optimize line breaks in metadata section

### ISSUE THREAD

**Issue by ipf** [tify-iiif-viewer/tify#6]
See this screenshot:
![auswahl_001](https://user-images.githubusercontent.com/557076/31327633-d994044a-acd0-11e7-8f6a-49746ee8ccb9.png)

**Comment by t11r** [comment]
Well, we have to break long words at some point. The only solution would be to drop the two-column layout – an option which I am actually considering. Yet even then could very long words be unfavorably wrapped.
