### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by ipf** [tify-iiif-viewer/tify#61]
see https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

Maybe the CI-Tools, such as Travis and AppVeyor and some Apps using `master` should be adjusted

**Comment by t11r** [comment]
Go ahead.

**Comment by ipf** [comment]
The master branch has been deleted, Appveyor and the some wording in the Ddocumentation were changed to use the `main` branch name from now on.
