### ISSUE TITLE
IIIF Image API not supported

### ISSUE THREAD

**Issue by cmahnke** [tify-iiif-viewer/tify#62]
Currently the IIIF Image API isn't supported. If one passes a `info.json` file generated by [`iiif_static.py`](https://github.com/zimeon/iiif/tree/master/demo-static) there is just an exception. 
The fact that there is just an exception but no error message is another issue...

```
TypeError: Cannot read property '0' of undefined
    at Ue.canvases (tify.js:12)
    at Kr.get (tify.js:12)
    at Kr.evaluate (tify.js:12)
    at Ue.canvases (tify.js:7)
    at s.hasOtherContent (tify.js:12)
    at Kr.get (tify.js:12)
    at Kr.evaluate (tify.js:12)
    at s.hasOtherContent (tify.js:7)
    at s.i (tify.js:12)
    at s.t._render (tify.js:12)
```

**Comment by ipf** [comment]
Currently TIFY only supports the IIIF Presentation API. For having a viewer consuming only the Image API I recomment https://github.com/mejackreed/Leaflet-IIIF

**Comment by cmahnke** [comment]
For the use case of presenting singe images via IIIF Image API [OpenLayers](https://openlayers.org/) is far better suited since it's better documented and has everything included, no plugins needed for IIIF, fullscreen and rotation. You get better results faster (compared to Leaflet)...
