### ISSUE TITLE
Check manifest for type and improve error handling

### ISSUE THREAD

**Issue by cmahnke** [tify-iiif-viewer/tify#63]
If one passes an unsupported IIIF API endpoint or just some JSON encoded rubbish, there is no real error handling.
There is an example to trigger this in #62.
It's better to catch the exception and report possible causes to the user.

**Comment by ipf** [comment]
Indeed, the Error Handling may be improved. An Example for just silently failing is http://demo.tify.rocks/demo?manifest=https://images.sub.uni-goettingen.de/iiif/image/gdz:PPN497825848:00000001/info.json
@paulpestov Could you have a look at that?

**Comment by ipf** [comment]
Resolved with #69
