### ISSUE TITLE
How to use multiple Tify instances on one page?

### ISSUE THREAD

**Issue by cmahnke** [tify-iiif-viewer/tify#64]
Currently it seems to be impossible to use multiple instances of Tify on one page. Additionally there is either no API documentation or no real API at all. The goal should be something like:
```
var tify1 = new Tify({"manifest": "https://example.com/iiif/manifest.json", "container": "#viewer", "init": true})
```

* Please take into consideration to foster reuse by thinking Tify as a widget, not as an application and design the initialisation accordingly.
* Enhance the developer documentation to describe how this can archived.

**Comment by ipf** [comment]
At the moment there is no real API at all.
@paulpestov Any ideas for integrating this?

**Comment by t11r** [comment]
There have already been several requests for a rudimentary API, and I would implement this along with making TIFY instantiable.

**Comment by t11r** [comment]
The lastest release supports multiple instances.
