### ISSUE TITLE
End-to-end tests not working

### ISSUE THREAD

**Issue by t11r** [tify-iiif-viewer/tify#72]
In the current `main` branch, E2E tests are no longer working. Each test fails with this error message:
```
"before each" hook: codeceptjs.before for "Change view via buttons @smoke":
     Can't connect to WebDriver.
Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 83
```

If there are additional steps to run for E2E tests to work, please update the readme.

**Comment by ipf** [comment]
Fixed with #76
