### ISSUE TITLE
New option: Render toolbar

### ISSUE THREAD

**Issue by polyrainbow** [tify-iiif-viewer/tify#8]
An option that enables/disables the toolbar at the top would be a nice addition.

When integrating TIFY in our application, we had to hide the toolbar by manually adjusting the minified CSS. Before that it looked like this:

![unbenannt](https://user-images.githubusercontent.com/5648131/33326046-22dfff78-d454-11e7-9056-884b45d7d0fc.png)

**Comment by t11r** [comment]
An option to hide the toolbar would only make sense if TIFY exposed all functions that as of now can only be controlled via the toolbar. While this would indeed be a nice feature, there are to plans to implement it in the near future.

However, if the container width does not match the viewport’s, CSS media queries lead to awkward results, as shown in your screenshot. With the next release, TIFY will evaluate the actual container width instead.

For hiding any part of the UI, you would still have to rely on additional CSS. It might be an option to include TIFY’s SCSS files into your stylesheet and modify them as needed.

**Comment by t11r** [comment]
With the current release v0.20.0, the toolbar should look fine in your case. To remove it, you still need some CSS as described above.

**Comment by hrvoj3e** [comment]
+1 for toolbar options in JS

**Comment by t11r** [comment]
Add CSS `.tify-header { display: none }` to hide the header. All related issues should be addressed with the latest release.
