### ISSUE TITLE
Add support for IIIF Presentation and Image API v3

### ISSUE THREAD

**Issue by ipf** [tify-iiif-viewer/tify#83]
see https://iiif.io/api/presentation/3.0/change-log/

The viewer should be able to handle also the presentation version 2.1

**Comment by t11r** [comment]
Could you add this, and if not, any estimate on the effort?

**Comment by c2lknt** [comment]
The status of this issue is unclear... Will IIIF version 3.0 be supported?

**Comment by t11r** [comment]
Yes, we are currently working on it.

**Comment by germyparker** [comment]
Do you guys know what the timeline might be for this?  I have a project I'm hoping to launch in January/February and I'd love to use Tify, is there any chance the v3 version will be available by then?

**Comment by Hero-Solutions** [comment]
Hi, we are also looking forward to the release of IIIF version 3 so that we can discontinue legacy software for IIIF 2.

**Comment by dreerr** [comment]
Any news on IIIF Version 3.0?

**Comment by t11r** [comment]
Thanks for asking :smile:

IIIF 3 is almost completed, we are currently busy with internal testing. Expect a release in February.

**Comment by dreerr** [comment]
This makes us very happy ❤️❤️ Can we use the `iiif3` branch for testing on our side?

**Comment by t11r** [comment]
Not yet, we want to fix all known bugs first. I will let you know when we deem the code ready for public testing and gladly accept your help.

**Comment by t11r** [comment]
IIIF 3 is supported since TIFY v0.30.0.
