### ISSUE TITLE
ready event?

### ISSUE THREAD

**Issue by moritzschepp** [tify-iiif-viewer/tify#94]
Hey guys, great tool, I just deployed it on a server and it works great!

I was wondering if there is a way to get notified when the viewer is "ready". I found `Tify.loading` and the viewer seems to be ready once that is 0. However, something like `Tify.addEventListener('ready', ...)` would be nice.

Thanks again,
Moritz

**Comment by t11r** [comment]
May I ask what exactly you are planning to do with this event, and what should be considered as "ready"?

**Comment by moritzschepp** [comment]
Sure, I wanted to make Tify load a manifest and then navigate to the page for a specific canvas. I can conveniently use `Tify.canvases` for that but this is only populated once `Tify.loading === 0`. So now I'm doing (and that works):

```javascript
var waitForIt = function() {
  if (Tify.loading !== 0) {
    window.setTimeout(waitForIt, 200)
  } else {
    // ... find page for given canvas id then Tify.setPage(...)
  }
}
```

I was wondering if Tify triggers an event once `Tify.loading` hits 0.

**Comment by t11r** [comment]
You could use <a href="https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver">MutationObserver</a> to observe `.tify-app_loading`, which is only present in the DOM while TIFY is loading.

**Comment by moritzschepp** [comment]
Thank you for the suggestion, it would certainly work. I feel though, that this requires knowledge about the internals of Tify: I'd expect the DOM structure to change without notice which would break our page. In this regard, its kind of the same like with the setInterval hack. This is why I was asking if there is an "official" way to get notified. If there is no event notification system in Tify and if this is not a good fit for your roadmap, feel free to close this issue.

**Comment by t11r** [comment]
With the upcoming release, TIFY will expose the full API of OpenSeadragon, so you could tap into its events. Any breaking changes are conspicuously documented.

In any case, code contributions are always welcome :slightly_smiling_face:

Closing this for now.

**Comment by moritzschepp** [comment]
Thank you for the follow up, that sounds great!
