### ISSUE TITLE
Load new manifest

### ISSUE THREAD

**Issue by louffoster** [tify-iiif-viewer/tify#95]
I have an application where the user can change manifests on the fly. Changing window.Tify.options.manifest and calling window.Tify.init() does nothing.

Is there a way to do this?

**Comment by t11r** [comment]
Currently, I am afraid this is not possible.

With one of the next releases, TIFY will get a rudimentary API. We will consider adding a function for changing the manifest after load.

**Comment by t11r** [comment]
This is addressed in the current release.
