### ISSUE TITLE
Tify doesn't load from `defer` `<script>` tags

### ISSUE THREAD

**Issue by christianmahnke** [tify-iiif-viewer/tify#96]
Currently Tify using a quite shaky mechanism to figure out a base path:
https://github.com/tify-iiif-viewer/tify/blob/main/src/main.js#L60

This has an issue if the browser doesn't guarantee that a page has been completely loaded when the initialisation of Tify is triggered. This can be the [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer) attribute of a `<script>`tag.

The result of this issue can be that the language files can't be loaded since the guessed base path is empty.

Add configuration setting to be able to set this path manually.

**Comment by t11r** [comment]
Good point. As the comment in the linked file already suggests, we are aware that this may not be the optimal solution.

An option for setting the base path will be part of the next release.

**Comment by t11r** [comment]
This should be no longer an issue with the current release.
